/*
 * Created on 2017-10-13 ( Time 10:51:44 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
package com.league.factory.api.web.rest.jaxrs;

import java.util.LinkedList;
import java.util.List;

import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.Status;

//--- Entities
import com.league.factory.api.data.record.PlayerRecord;
import com.league.factory.api.data.record.listitem.PlayerListItem;
//--- Services 
import com.league.factory.api.persistence.PlayerPersistence;
// import com.league.factory.api.business.service.impl.PlayerServiceImpl;
import com.league.factory.api.persistence.commons.PersistenceServiceProvider;
import com.league.factory.api.web.rest.commons.AbstractResourceController;

/**
 * JAXRS Jersey controller for 'Player' management.
 */
@Path("/player")
public class PlayerResource extends AbstractResourceController {

	private PlayerPersistence playerService = PersistenceServiceProvider.getService(PlayerPersistence.class);

	/**
	 * Constructor
	 */
	public PlayerResource() {
		super();
		logger.info("Constructor.");
	}

	/**
	 * Get all player entities.
	 * @return list with all entities found
	 */
	@GET
	@Produces({MediaType.APPLICATION_JSON})
	public List<PlayerRecord> findAll() {
		logger.info("findAll()...");
		return playerService.findAll();
	}

	/**
	 * Retrieves a player using the given id.
	 * @param id id
	 * @return 200 + body if found, 404 if not found 
	 */
	@GET
	@Path("{id}")
	@Produces({MediaType.APPLICATION_JSON})
	public Response findById(@PathParam("id") long id) {
		logger.info("findById("+id+")...");
		PlayerRecord record = playerService.findById(id);
		if ( record != null ) {
			return Response.ok(record).build();
		}
		else {
			return Response.status(Status.NOT_FOUND).build();
		}
	}

	/**
	 * Creates a new player.
	 * @param player player
	 * @return 201 with body if created, 409 conflict if duplicate key 
	 */	
	@POST
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	public Response create(PlayerRecord player) {
		logger.info("create()...");
		if ( playerService.exists(player) ) {
			logger.info("create() : already exists -> conflict");
			return Response.status(Status.CONFLICT).build();
		}
		else {
			logger.info("create() : doesn't exist -> create");
			PlayerRecord record = playerService.create(player);
			return Response.status(Status.CREATED).entity(record).build();
		}
	}

//------------------------------------------------------------
	/**
	 * Updates the player identified by the given id
	 * @param player player entity
	 * @param id id 
	 * @return 200 if found and updated, 404 if not found 
	 */	
	@PUT
	@Path("{id}")
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	// public PlayerRecord update(PlayerRecord player, @PathParam("id") long id) {
	public Response update(PlayerRecord player, @PathParam("id") long id) {
		logger.info("update()...");
		// force the id (use the id provided by the URL)
		player.setId( id );
		boolean updated = playerService.update(player);
		if ( updated ) {
			// Actually updated (found and updated) => 200 OK
			return Response.status(Status.OK).build();
		}
		else {
			// Not updated with no error => 404 not found
			return Response.status(Status.NOT_FOUND).build();
		}
	}

	/**
	 * Save (create or update) the given player.
	 * @param player player entity
	 * @return 200 if found and updated, 201 if not found and created
	 */	
	@PUT
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	public Response save(PlayerRecord player) {
		logger.info("save()...");
		Status status = Status.OK ; // 200 OK
		if ( ! playerService.exists(player) ) {
			status = Status.CREATED ; // 201 CREATED
		}
		PlayerRecord record = playerService.save(player);
		// Response ( code 200 or 201 )
		return Response.status(status).entity(record).build();
	}


//------------------------------------------------------------
	/**
	 * Delete a player.
	 * @param id id
	 */
	@DELETE
	@Path("{id}")
	//@Consumes({MediaType.APPLICATION_JSON})
	// public void delete(@PathParam("id") long id) {
	public Response delete(@PathParam("id") long id) {
		logger.info("delete("+id+")...");
		// playerService.deleteById(id);
		boolean deleted = playerService.deleteById(id);
		if ( deleted ) {
			// Actually deleted (found and deleted) => 204 "No Content" because no body in the response 
			return Response.status(Status.NO_CONTENT).build();
		}
		else {
			// Not deleted with no error => 404 "Not found"
			return Response.status(Status.NOT_FOUND).build();
		}
}

	@GET
	@Path("/players-list-items")
	@Produces({MediaType.APPLICATION_JSON})
	public List<PlayerListItem> listItems() {
		logger.info("listItems()...");
		List<PlayerRecord> list = playerService.findAll();
		List<PlayerListItem> items = new LinkedList<PlayerListItem>();
		for ( PlayerRecord player : list ) {
			items.add(new PlayerListItem( player ) );
		}
		return items;
	}

}
