/*
 * Created on 2017-10-13 ( Date ISO 2017-10-13 - Time 10:51:30 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package com.league.factory.api.persistence;

import java.util.List;

import com.league.factory.api.data.record.PlayerRecord;

/**
 * Persistence Interface for PlayerRecord.
 */
public interface PlayerPersistence { 

	/**
	 * Tries to find an entity using its Id / Primary Key
	 * @param id
	 * @return entity
	 */
	PlayerRecord findById( Long id  ) ;

	/**
	 * Finds all entities.
	 * @return all entities
	 */
	List<PlayerRecord> findAll();

	/**
	 * Counts all the records present in the database
	 * @return
	 */
	public long countAll() ;


	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	PlayerRecord save(PlayerRecord entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return true if the entity has been updated, false if not found and not updated
	 */
	boolean update(PlayerRecord entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	PlayerRecord create(PlayerRecord entity);

	/**
	 * Deletes an entity using its Id / Primary Key
	 * @param id
	 * @return true if the entity has been deleted, false if not found and not deleted
	 */
	boolean deleteById( Long id );

	/**
	 * Deletes an entity using the Id / Primary Key stored in the given object
	 * @param the entity to be deleted (supposed to have a valid Id/PK )
	 * @return true if the entity has been deleted, false if not found and not deleted
	 */
	boolean delete( PlayerRecord entity );

	/**
	 * Returns true if an entity exists with the given Id / Primary Key 
	 * @param id
	 * @return
	 */
	public boolean exists( Long id ) ;

	/**
	 * Returns true if the given entity exists
	 * @param entity
	 * @return
	 */
	public boolean exists( PlayerRecord entity ) ;

}
