/*
 * Created on 2017-10-13 ( Date ISO 2017-10-13 - Time 10:51:30 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package com.league.factory.api.data.record.listitem;

import com.league.factory.api.commons.ListItem;
import com.league.factory.api.data.record.PlayerRecord;

public class PlayerListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public PlayerListItem(PlayerRecord player) {
		super();

		this.value = ""
			 + player.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = player.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
