/*
 * Created on 2017-10-13 ( Date ISO 2017-10-13 - Time 10:51:45 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package com.league.factory.api.web.rest.commons;

import java.util.logging.Logger;

/**
 * Abstract REST resource controller providing a logger <br>
 *  
 * @author Telosys
 *
 */
public abstract class AbstractResourceController {

	protected final Logger logger ;
	
	/**
	 * Constructor
	 */
	public AbstractResourceController() {
		super();
		this.logger = Logger.getLogger(this.getClass().getCanonicalName()); 

		this.logger.setLevel(LoggerLevel.LEVEL);
	}
}
