/*
 * Created on 2017-10-13 ( Date ISO 2017-10-13 - Time 10:51:44 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package com.league.factory.api.web.rest.commons;

import java.util.logging.Level;

/**
 * The logger level <br>
 * 
 * @author Telosys
 *
 */
public class LoggerLevel {

	// Set the logger level here :
	
	//public final static Level LEVEL = Level.OFF ;
	public final static Level LEVEL = Level.ALL ;
	
}
