/*
 * Created on 2017-10-13 ( Date ISO 2017-10-13 - Time 10:51:31 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */


package com.league.factory.api.data.record;

import java.io.Serializable;

import javax.validation.constraints.NotNull;


/**
 * Java bean for entity "Team" <br>
 * Contains only "wrapper types" (no primitive types) <br>
 * Can be used both as a "web form" and "persistence record" <br>
 * 
 * @author Telosys Tools Generator
 *
 */
public class TeamRecord implements Serializable
{
    private static final long serialVersionUID = 1L;

    @NotNull
    private Long id ; // long // Id or Primary Key


    private String name ;  // String 

    /**
     * Default constructor
     */
    public TeamRecord() {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR ID OR PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "id" field value
     * This field is mapped on the database column "id" ( type "", NotNull : true ) 
     * @param id
     */
	public void setId( Long id ) {
        this.id = id ;
    }
    /**
     * Get the "id" field value
     * This field is mapped on the database column "id" ( type "", NotNull : true ) 
     * @return the field value
     */
	public Long getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR OTHER DATA FIELDS 
    //----------------------------------------------------------------------

    /**
     * Set the "name" field value
     * This field is mapped on the database column "name" ( type "", NotNull : false ) 
     * @param name
     */
    public void setName( String name ) {
        this.name = name;
    }
    /**
     * Get the "name" field value
     * This field is mapped on the database column "name" ( type "", NotNull : false ) 
     * @return the field value
     */
    public String getName() {
        return this.name;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(name);
        return sb.toString(); 
    } 



}
