/*
 * Created on 2017-10-13 ( Date ISO 2017-10-13 - Time 10:51:36 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package com.league.factory.api.persistence.impl.jpa.mapper;

import com.league.factory.api.data.record.PlayerRecord; // "Neutral Record" class 
import com.league.factory.api.persistence.impl.jpa.commons.AbstractServiceMapper;
import com.league.factory.api.persistence.impl.jpa.record.PlayerJpaRecord; // "JPA Entity" class 

/**
 * Mapping between entity beans and display beans.
 */
public class PlayerJpaMapper extends AbstractServiceMapper {



	/**
	 * Constructor.
	 */
	public PlayerJpaMapper() {
		super();
	}


	/**
	 * Mapping from 'PlayerJpaRecord' to 'PlayerRecord'
	 * @param entity the mapping input 
	 */
	public PlayerRecord mapEntityToRecord ( PlayerJpaRecord entity) {
		if ( entity == null ) {
			return null;
		}

		//--- Generic mapping 
		PlayerRecord record = map(entity, PlayerRecord.class);

		return record ;
	}

	/**
	 * Mapping from 'PlayerRecord' to 'PlayerJpaRecord' 
	 * @param record the mapping input 
	 * @return
	 */
	public PlayerJpaRecord mapRecordToEntity(PlayerRecord record) {
		if ( record == null ) {
			return null;
		}
		return map(record, PlayerJpaRecord.class);
	}


	/**
	 * Mapping from record 'PlayerRecord' to entity 'PlayerJpaRecord'
	 * @param record
	 * @param entity
	 */
	public void mapRecordToEntity(PlayerRecord record, PlayerJpaRecord entity) {
		if ( record == null ) {
			return;
		}

		//--- Generic mapping 
		map(record, entity);
	}


}