/*
 * Created on 2017-10-13 ( Date ISO 2017-10-13 - Time 10:51:36 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package com.league.factory.api.persistence.impl.jpa.mapper;

import com.league.factory.api.data.record.TeamRecord; // "Neutral Record" class 
import com.league.factory.api.persistence.impl.jpa.commons.AbstractServiceMapper;
import com.league.factory.api.persistence.impl.jpa.record.TeamJpaRecord; // "JPA Entity" class 

/**
 * Mapping between entity beans and display beans.
 */
public class TeamJpaMapper extends AbstractServiceMapper {



	/**
	 * Constructor.
	 */
	public TeamJpaMapper() {
		super();
	}


	/**
	 * Mapping from 'TeamJpaRecord' to 'TeamRecord'
	 * @param entity the mapping input 
	 */
	public TeamRecord mapEntityToRecord ( TeamJpaRecord entity) {
		if ( entity == null ) {
			return null;
		}

		//--- Generic mapping 
		TeamRecord record = map(entity, TeamRecord.class);

		return record ;
	}

	/**
	 * Mapping from 'TeamRecord' to 'TeamJpaRecord' 
	 * @param record the mapping input 
	 * @return
	 */
	public TeamJpaRecord mapRecordToEntity(TeamRecord record) {
		if ( record == null ) {
			return null;
		}
		return map(record, TeamJpaRecord.class);
	}


	/**
	 * Mapping from record 'TeamRecord' to entity 'TeamJpaRecord'
	 * @param record
	 * @param entity
	 */
	public void mapRecordToEntity(TeamRecord record, TeamJpaRecord entity) {
		if ( record == null ) {
			return;
		}

		//--- Generic mapping 
		map(record, entity);
	}


}