/*
 * Created on 2017-10-13 ( Date ISO 2017-10-13 - Time 10:51:31 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package com.league.factory.api.data.record;


import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for bean PlayerRecord
 * 
 * @author Telosys Tools Generator
 *
 */
public class PlayerRecordTest 
{

	@Test
	public void testSettersAndGetters() {
		
		System.out.println("Checking class PlayerRecord getters and setters ..." );
		
		PlayerRecord playerRecord = new PlayerRecord();


		//--- Test setter/getter for attribute "id"  ( model type : long / wrapperType : Long )
		playerRecord.setId( 1000L ) ;
		Assert.assertTrue(  1000L == playerRecord.getId()  ) ; // Primitive type in model


		//--- Test setter/getter for attribute "name"  ( model type : String / wrapperType : String )
		playerRecord.setName( "A" ) ;
		Assert.assertEquals( "A", playerRecord.getName() ) ; // Not primitive type in model


		//--- Test setter/getter for attribute "team"  ( model type : Long / wrapperType : Long )
		playerRecord.setTeam( Long.valueOf(1000L) ) ;
		Assert.assertEquals( Long.valueOf(1000L), playerRecord.getTeam() ) ; // Not primitive type in model


	}

}
