/*
 * Created on 2017-10-13 ( Date ISO 2017-10-13 - Time 10:51:31 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package com.league.factory.api.data.record;


import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for bean TeamRecord
 * 
 * @author Telosys Tools Generator
 *
 */
public class TeamRecordTest 
{

	@Test
	public void testSettersAndGetters() {
		
		System.out.println("Checking class TeamRecord getters and setters ..." );
		
		TeamRecord teamRecord = new TeamRecord();


		//--- Test setter/getter for attribute "id"  ( model type : long / wrapperType : Long )
		teamRecord.setId( 1000L ) ;
		Assert.assertTrue(  1000L == teamRecord.getId()  ) ; // Primitive type in model


		//--- Test setter/getter for attribute "name"  ( model type : String / wrapperType : String )
		teamRecord.setName( "A" ) ;
		Assert.assertEquals( "A", teamRecord.getName() ) ; // Not primitive type in model


	}

}
