/*
 * Created on 2017-10-13 ( Date ISO 2017-10-13 - Time 10:51:37 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package com.league.factory.api.persistence.impl.jpa;

import org.junit.Test;

import com.league.factory.api.persistence.TeamPersistence ;
import com.league.factory.api.persistence.TeamPersistenceGenericTest;

/**
 * JUnit tests for Team persistence service
 * 
 * @author Telosys Tools
 *
 */
public class TeamPersistenceJpaTest extends TeamPersistenceGenericTest {

	@Test
	public void testPersistenceService() {

    	TeamPersistence persistenceService = new TeamPersistenceJpa();


    	testPersistenceServiceWithAutoincrementedKey(persistenceService);
	}	
}
