/*
 * Created on 2017-10-13 ( Date ISO 2017-10-13 - Time 10:51:36 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package com.league.factory.api.persistence.impl.jpa;


import java.util.List;

import javax.inject.Named;

import com.league.factory.api.data.record.PlayerRecord; // "Neutral Record" class 
import com.league.factory.api.persistence.PlayerPersistence; // Persistence service interface
import com.league.factory.api.persistence.impl.jpa.commons.GenericJpaService;
import com.league.factory.api.persistence.impl.jpa.mapper.PlayerJpaMapper ;
import com.league.factory.api.persistence.impl.jpa.record.PlayerJpaRecord; // "JPA Record" class (with JPA mapping) 

/**
 * Player persistence service - JPA implementation 
 * 
 * @author Telosys 
 *
 */
@Named("PlayerPersistence")
public class PlayerPersistenceJpa extends GenericJpaService<PlayerJpaRecord, Long> implements PlayerPersistence {

	private final PlayerJpaMapper mapper = new PlayerJpaMapper();

	/**
	 * Constructor
	 */
	public PlayerPersistenceJpa() {
		super(PlayerJpaRecord.class);
	}

	@Override
	public PlayerRecord findById( Long id ) {
		PlayerJpaRecord entity = super.find( id );
		return mapper.mapEntityToRecord(entity);	
	}

	@Override
	public List<PlayerRecord> findAll() {
		List<PlayerJpaRecord> entities = super.loadAll() ;
		List<PlayerRecord> records = new java.util.LinkedList<PlayerRecord>();
		for ( PlayerJpaRecord entity : entities ) {
			records.add( mapper.mapEntityToRecord(entity) ) ;
		}
		return records ;
	}

	@Override
	public PlayerRecord create(PlayerRecord record) {
		PlayerJpaRecord entity = mapper.mapRecordToEntity(record);
		super.persist(entity);
		// Auto-incremented key : set the generated id in the original record
		record.setId( entity.getId() ) ;
		//record.setId(entity.getId());
		return record ;
	}
	
	@Override
	public boolean update(PlayerRecord record) {
		Long pk = record.getId() ;
		if ( super.find( pk ) != null ) {
			// Exists => 'merge' 
			PlayerJpaRecord entity = mapper.mapRecordToEntity(record);
			super.merge(entity);
			return true ;
		}
		else {
			return false;
		}
	}

	@Override
	public PlayerRecord save(PlayerRecord record) {
		PlayerJpaRecord entity = mapper.mapRecordToEntity(record);
		super.merge(entity);
		return record ;
	}

	@Override
	public boolean deleteById( Long id ) {
		return super.remove( id );
	}

	@Override
	public boolean delete(PlayerRecord record) {
		if ( record != null ) {
			return super.remove( record.getId() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		Long count = (Long) super.execNamedQueryWithSingleResult( buildQueryName("countAll") ) ;
		return count.longValue();
	}

	public long countById(Long id) {
		Long count = (Long) super.execNamedQueryWithSingleResult( buildQueryName("countById"), id ) ;
		return count.longValue();
	}
	
	@Override
	public boolean exists(Long id) {
		long count = countById(id) ;
		return count > 0 ;
	}


	@Override
	public boolean exists(PlayerRecord record) {
		if ( record != null ) {
			return exists( record.getId() );
		}
		return false ;
	}

	@SuppressWarnings("unchecked")
	public List<PlayerJpaRecord> queryExample() {
		List<?> list = super.execNamedQuery(buildQueryName("theNamedQueryToBeUsed")) ;
		return (List<PlayerJpaRecord>) list ;
	}

}
