/*
 * Created on 2017-10-13 ( Date ISO 2017-10-13 - Time 10:51:37 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package com.league.factory.api.persistence.impl.jpa;


import java.util.List;

import javax.inject.Named;

import com.league.factory.api.data.record.TeamRecord; // "Neutral Record" class 
import com.league.factory.api.persistence.TeamPersistence; // Persistence service interface
import com.league.factory.api.persistence.impl.jpa.commons.GenericJpaService;
import com.league.factory.api.persistence.impl.jpa.mapper.TeamJpaMapper ;
import com.league.factory.api.persistence.impl.jpa.record.TeamJpaRecord; // "JPA Record" class (with JPA mapping) 

/**
 * Team persistence service - JPA implementation 
 * 
 * @author Telosys 
 *
 */
@Named("TeamPersistence")
public class TeamPersistenceJpa extends GenericJpaService<TeamJpaRecord, Long> implements TeamPersistence {

	private final TeamJpaMapper mapper = new TeamJpaMapper();

	/**
	 * Constructor
	 */
	public TeamPersistenceJpa() {
		super(TeamJpaRecord.class);
	}

	@Override
	public TeamRecord findById( Long id ) {
		TeamJpaRecord entity = super.find( id );
		return mapper.mapEntityToRecord(entity);	
	}

	@Override
	public List<TeamRecord> findAll() {
		List<TeamJpaRecord> entities = super.loadAll() ;
		List<TeamRecord> records = new java.util.LinkedList<TeamRecord>();
		for ( TeamJpaRecord entity : entities ) {
			records.add( mapper.mapEntityToRecord(entity) ) ;
		}
		return records ;
	}

	@Override
	public TeamRecord create(TeamRecord record) {
		TeamJpaRecord entity = mapper.mapRecordToEntity(record);
		super.persist(entity);
		// Auto-incremented key : set the generated id in the original record
		record.setId( entity.getId() ) ;
		//record.setId(entity.getId());
		return record ;
	}
	
	@Override
	public boolean update(TeamRecord record) {
		Long pk = record.getId() ;
		if ( super.find( pk ) != null ) {
			// Exists => 'merge' 
			TeamJpaRecord entity = mapper.mapRecordToEntity(record);
			super.merge(entity);
			return true ;
		}
		else {
			return false;
		}
	}

	@Override
	public TeamRecord save(TeamRecord record) {
		TeamJpaRecord entity = mapper.mapRecordToEntity(record);
		super.merge(entity);
		return record ;
	}

	@Override
	public boolean deleteById( Long id ) {
		return super.remove( id );
	}

	@Override
	public boolean delete(TeamRecord record) {
		if ( record != null ) {
			return super.remove( record.getId() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		Long count = (Long) super.execNamedQueryWithSingleResult( buildQueryName("countAll") ) ;
		return count.longValue();
	}

	public long countById(Long id) {
		Long count = (Long) super.execNamedQueryWithSingleResult( buildQueryName("countById"), id ) ;
		return count.longValue();
	}
	
	@Override
	public boolean exists(Long id) {
		long count = countById(id) ;
		return count > 0 ;
	}


	@Override
	public boolean exists(TeamRecord record) {
		if ( record != null ) {
			return exists( record.getId() );
		}
		return false ;
	}

	@SuppressWarnings("unchecked")
	public List<TeamJpaRecord> queryExample() {
		List<?> list = super.execNamedQuery(buildQueryName("theNamedQueryToBeUsed")) ;
		return (List<TeamJpaRecord>) list ;
	}

}
