/*
 * Created on 2017-10-13 ( Date ISO 2017-10-13 - Time 10:51:30 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package com.league.factory.api.persistence.impl.fake;

import java.util.List;

import javax.inject.Named;

import com.league.factory.api.data.record.PlayerRecord;
import com.league.factory.api.persistence.PlayerPersistence;
import com.league.factory.api.persistence.impl.fake.commons.GenericFakeDAO;

/**
 * Player persistence service - FAKE implementation 
 * 
 * @author Telosys
 *
 */
@Named("PlayerPersistence")
public class PlayerPersistenceFake extends GenericFakeDAO<PlayerRecord> implements PlayerPersistence {

	/**
	 * Constructor
	 */
	public PlayerPersistenceFake() {
		super(PlayerRecord.class);
	}

	/**
	 * Creates a new bean instance and set its primary key value(s)
	 * 
	 * @param id
	 * @return the new instance
	 */
	private PlayerRecord newInstanceWithPrimaryKey(long id) {
		PlayerRecord record = new PlayerRecord();
        record.setId(id); 
		return record;
	}

	//-------------------------------------------------------------------------------------
	// Generic DAO abstract methods implementations
	//-------------------------------------------------------------------------------------
	@Override
	protected String getKey(PlayerRecord record) {
		return buildKeyString(record.getId());
	}
	
	@Override
	protected void setAutoIncrementedKey(PlayerRecord record, long value) {
		//record.setId((long)value);
		record.setId(value);
	}

	//-------------------------------------------------------------------------------------
	// Persistence interface implementations
	//-------------------------------------------------------------------------------------
	@Override
	public long countAll() {
		return super.doCountAll();
	}
	
	@Override
	public PlayerRecord create(PlayerRecord record) {
		super.doCreateAutoIncremented(record);
		return record;
	}

	@Override
	public boolean delete(PlayerRecord record) {
		return super.doDelete(record);
	}

	@Override
	public boolean deleteById(Long id) {
		PlayerRecord record = newInstanceWithPrimaryKey(id);
		return super.doDelete(record);
	}

	@Override
	public boolean exists(PlayerRecord record) {
		return super.doExists(record);
	}

	@Override
	public boolean exists(Long id) {
		PlayerRecord record = newInstanceWithPrimaryKey(id);
		return super.doExists(record);
	}

	@Override
	public List<PlayerRecord> findAll() {
		return super.doFindAll();
	}

	@Override
	public PlayerRecord findById(Long id) {
        PlayerRecord record = newInstanceWithPrimaryKey(id);
		return super.doFind(record);
	}

	@Override
	public PlayerRecord save(PlayerRecord record) {
		if (super.doExists(record)) {
			super.doUpdate(record);
		} else {
			super.doCreateAutoIncremented(record);
		}
        return record;
	}

	@Override
	public boolean update(PlayerRecord record) {
		return super.doUpdate(record);	
	}
}
