/*
 * Created on 2017-10-13 ( Date ISO 2017-10-13 - Time 10:51:31 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package com.league.factory.api.persistence.impl.fake;

import java.util.List;

import javax.inject.Named;

import com.league.factory.api.data.record.TeamRecord;
import com.league.factory.api.persistence.TeamPersistence;
import com.league.factory.api.persistence.impl.fake.commons.GenericFakeDAO;

/**
 * Team persistence service - FAKE implementation 
 * 
 * @author Telosys
 *
 */
@Named("TeamPersistence")
public class TeamPersistenceFake extends GenericFakeDAO<TeamRecord> implements TeamPersistence {

	/**
	 * Constructor
	 */
	public TeamPersistenceFake() {
		super(TeamRecord.class);
	}

	/**
	 * Creates a new bean instance and set its primary key value(s)
	 * 
	 * @param id
	 * @return the new instance
	 */
	private TeamRecord newInstanceWithPrimaryKey(long id) {
		TeamRecord record = new TeamRecord();
        record.setId(id); 
		return record;
	}

	//-------------------------------------------------------------------------------------
	// Generic DAO abstract methods implementations
	//-------------------------------------------------------------------------------------
	@Override
	protected String getKey(TeamRecord record) {
		return buildKeyString(record.getId());
	}
	
	@Override
	protected void setAutoIncrementedKey(TeamRecord record, long value) {
		//record.setId((long)value);
		record.setId(value);
	}

	//-------------------------------------------------------------------------------------
	// Persistence interface implementations
	//-------------------------------------------------------------------------------------
	@Override
	public long countAll() {
		return super.doCountAll();
	}
	
	@Override
	public TeamRecord create(TeamRecord record) {
		super.doCreateAutoIncremented(record);
		return record;
	}

	@Override
	public boolean delete(TeamRecord record) {
		return super.doDelete(record);
	}

	@Override
	public boolean deleteById(Long id) {
		TeamRecord record = newInstanceWithPrimaryKey(id);
		return super.doDelete(record);
	}

	@Override
	public boolean exists(TeamRecord record) {
		return super.doExists(record);
	}

	@Override
	public boolean exists(Long id) {
		TeamRecord record = newInstanceWithPrimaryKey(id);
		return super.doExists(record);
	}

	@Override
	public List<TeamRecord> findAll() {
		return super.doFindAll();
	}

	@Override
	public TeamRecord findById(Long id) {
        TeamRecord record = newInstanceWithPrimaryKey(id);
		return super.doFind(record);
	}

	@Override
	public TeamRecord save(TeamRecord record) {
		if (super.doExists(record)) {
			super.doUpdate(record);
		} else {
			super.doCreateAutoIncremented(record);
		}
        return record;
	}

	@Override
	public boolean update(TeamRecord record) {
		return super.doUpdate(record);	
	}
}
